class ApiData
	#Here in case the API URL breaks
	def self.pokemon
		["bulbasaur","ivysaur","venusaur","charmander","charmeleon","charizard", "wartortle",
 "blastoise","caterpie", "metapod", "butterfree", "weedle","kakuna",
 "pidgey", "pidgeotto", "pidgeot", "rattata", "raticate", "spearow", "fearow",
 "ekans", "arbok", "pikachu", "raichu", "sandshrew", "sandslash", "nidoran-f",
 "nidorina", "nidoqueen", "nidoran-m", "nidorino", "nidoking", "clefairy",
 "clefable", "vulpix","ninetales", "jigglypuff","wigglytuff", "golbat",
 "oddish", "gloom", "vileplume", "paras", "parasect", "venonat", "venomoth",
 "diglett", "dugtrio", "meowth", "persian","psyduck", "golduck", "mankey",
 "primeape", "growlithe", "arcanine", "poliwag", "poliwhirl", "poliwrath",
 "abra", "kadabra", "alakazam", "machop", "machoke", "machamp", "bellsprout",
 "weepinbell", "victreebel", "tentacool", "tentacruel", "geodude", "graveler",
 "golem", "ponyta", "rapidash", "slowpoke", "slowbro", "magnemite", "magneton",
 "farfetchd", "doduo", "dodrio", "seel", "dewgong", "grimer", "muk", "shellder",
 "cloyster", "gastly","haunter", "gengar",
 "onix", "drowzee", "hypno","krabby", "kingler", "voltorb"]
	end

	def self.yugioh
		["A Feint Plan",
 "A Hero Emerges",
 "A Major Upset",
 "A Rival Appears!",
 "A.I. Shadow",
 "Abominable Chamber of the Unchained",
 "Absolute End",
 "Abyss Actors Back Stage",
 "Abyss Actors' Curtain Call",
 "Abyss Stungray",
 "Abyss-scorn",
 "Abyss-sphere",
 "Abyss-squall",
 "Abyss-strom",
 "Accumulated Fortune",
 "Acid Trap Hole",
 "Adhesion Trap Hole",
 "Aegis of Gaia",
 "Aegis of the Ocean Dragon Lord",
 "Aerial Recharge",
 "Alchemy Cycle",
 "Alien Brain",
 "All-Out Attacks",
 "Altar for Tribute",
 "Altergeist Camouflage",
 "Altergeist Emulatelf",
 "Altergeist Failover",
 "Altergeist Haunted Rock",
 "Altergeist Manifestation",
 "Altergeist Protocol",
 "Amazoness Archers",
 "Amazoness Onslaught",
 "Amazoness Shamanism",
 "Amazoness Willpower",
 "Ambush Fangs",
 "Amorphage Lysis",
 "An Unfortunate Report",
 "Ancient Gear Reborn",
 "And the Band Played On",
 "Anti Raigeki",
 "Anti-Fusion Device",
 "Anti-Magic Prism",
 "Anti-Spell",
 "Anti-Spell Fragrance",
 "Apparition",
 "Apple of Enlightenment",
 "Appointer of the Red Lotus",
 "Appropriate",
 "Aqua Chorus",
 "Aqua Story - Urashima",
 "Aquamirror Cycle",
 "Aquamirror Illusion",
 "Aquamirror Meditation",
 "Arcana Call",
 "Archfiend's Roar",
 "Armageddon Designator",
 "Armor Break",
 "Armor Ninjitsu Art of Freezing",
 "Armor Ninjitsu Art of Rust Mist",
 "Armored Glass",
 "Armory Call",
 "Arsenal Robber",
 "Artifact Sanctum",
 "Asleep at the Switch",
 "Assault Counter",
 "Assault Mode Activate",
 "Assault on GHQ",
 "Assault Reboot",
 "Assault Slash",
 "Assault Spirits",
 "Astral Barrier",
 "At One With the Sword",
 "Attack and Receive",
 "Attack of the Cornered Rat",
 "Attack Reflector Unit",
 "Attention!",
 "Automatic Laser",
 "Avalon",
 "Awakening of Nephthys",
 "Back to the Front",
 "Backfire",
 "Backs to the Wall",
 "Backup Soldier",
 "Bad Aim",
 "Bad Luck Blast",
 "Bad Reaction to Simochi",
 "Balance of Judgment",
 "Ballista Squad",
 "Bamboo Scrap",
 "Bark of Dark Ruler",
 "Barrage Blast",
 "Barrel Behind the Door",
 "Barrier Wave",
 "Battle Break",
 "Battle Instinct",
 "Battle Mania",
 "Battle of the Elements",
 "Battle Teleportation",
 "Battle-Scarred",
 "Battleguard Howling",
 "Battleguard Rage",
 "Battlewasp - Nest",
 "Beast Rising",
 "Beast Soul Swap",
 "Beckoning Light",
 "Beginning of Heaven and Earth",
 "Begone, Knave!",
 "Bending Destiny",
 "Berserking",
 "Big Burn",
 "BIG Win!?",
 "Birthright",
 "Black Cat-astrophe",
 "Black Feather Beacon",
 "Black Horn of Heaven",
 "Black Illusion",
 "Black Return",
 "Black Sonic",
 "Black Thunder",
 "Black Wing Revenge",
 "Blackback",
 "Blackbird Close",
 "Blackboost",
 "Blackwing - Backlash",
 "Blackwing - Bombardment",
 "Blackwing - Boobytrap",
 "Blast Held by a Tribute",
 "Blast with Chain",
 "Blasting Fuse",
 "Blasting the Ruins",
 "Blaze Accelerator Reload",
 "Blazing Mirror Force",
 "Blessed Winds",
 "Blessings for Gusto",
 "Blind Destruction",
 "Blind Obliteration",
 "Blooming of the Darkest Rose",
 "Blossom Bombardment",
 "Bonding - DHO",
 "Bone Temple Block",
 "Booby Trap E",
 "Boompoline!!",
 "Boot-Up Order - Gear Force",
 "Born from Draconis",
 "Borrel Cooling",
 "Bottomless Shifting Sand",
 "Bottomless Trap Hole",
 "Bounzer Guard",
 "Brain Hazard",
 "Brainwashing Beam",
 "Break Away",
 "Break Off Trap Hole",
 "Breakthrough Skill",
 "Breakthrough!",
 "Bright Future",
 "Brilliant Spark",
 "Broken Blocker",
 "Broken Line",
 "Brutal Beast Battle",
 "Brutal Potion",
 "Bubble Bringer",
 "Bubble Crash",
 "Bug Emergency",
 "Bujin Regalia - The Jewel",
 "Bujin Regalia - The Sword",
 "Bujincident",
 "Bujinfidel",
 "Burgeoning Whirlflame",
 "Burnout",
 "Burst Breath",
 "Burst Rebirth",
 "Butterflyoke",
 "Butterspy Protection",
 "By Order of the Emperor",
 "Bye Bye Damage",
 "Byroad Sacrifice",
 "Call of Darkness",
 "Call of the Archfiend",
 "Call of the Earthbound",
 "Call of the Grave",
 "Call of the Haunted",
 "Call of the Reaper",
 "Card of Sacrifice",
 "Cash Back",
 "Castle of Dragon Souls",
 "Castle Walls",
 "Catch Copy",
 "Ceasefire",
 "Cell Explosion Virus",
 "Cemetary Bomb",
 "Chain Burst",
 "Chain Destruction",
 "Chain Detonation",
 "Chain Disappearance",
 "Chain Dispel",
 "Chain Healing",
 "Chain Hole",
 "Chain Ignition",
 "Chain Material",
 "Chain Whirlwind",
 "Champion's Vigilance",
 "Change of Hero - Reflector Ray",
 "Changing Destiny",
 "Chaos Burst",
 "Chaos Infinity",
 "Chaos Trap Hole",
 "Chivalry",
 "Chosen of Zefra",
 "Chthonian Blast",
 "Chthonian Polymer",
 "Cipher Bit",
 "Cipher Spectrum",
 "Clay Charge",
 "Cloak and Dagger",
 "Cloning",
 "Cocoon Veil",
 "Coffin Seller",
 "Collected Power",
 "Command Performance",
 "Commander of Swords",
 "Common Charity",
 "Compulsory Escape Device",
 "Compulsory Evacuation Device",
 "Confusion Chaff",
 "Conscription",
 "Consolation Prize",
 "Constellar Meteor",
 "Contract Laundering",
 "Converging Wishes",
 "Copy Knight",
 "Core Blast",
 "Core Reinforcement",
 "Corrosive Scales",
 "Corrupted Keys",
 "Counter Counter",
 "Counter Gate",
 "Counter Gem",
 "Counterforce",
 "Covering Fire",
 "Crackdown",
 "Crevice Into the Different Dimension",
 "Crimson Fire",
 "Crop Circles",
 "Cross Counter",
 "Cross-Dimensional Duel",
 "Crusadia Krawler",
 "Crusadia Vanguard",
 "Crush Card Virus",
 "Crusher Run",
 "Cry Havoc!",
 "Crystal Conclave",
 "Crystal Pair",
 "Crystal Raigeki",
 "Crystron Entry",
 "Crystron Impact",
 "Cubic Ascension",
 "Cubic Mandala",
 "Cubic Omen",
 "Cubic Rebirth",
 "Curse of Aging",
 "Curse of Anubis",
 "Curse of Darkness",
 "Curse of Royal",
 "Curse of the Circle",
 "Cursed Seal of the Forbidden Spell",
 "Cyber Network",
 "Cyber Shadow Gardna",
 "Cyber Summon Blaster",
 "Cybernetic Hidden Technology",
 "Cybernetic Overflow",
 "Cybernetic Revolution",
 "Cyberse Beacon",
 "Cynet Cascade",
 "Cynet Conflict",
 "Cynet Refresh",
 "Cynet Regression",
 "D - Chain",
 "D - Counter",
 "D - Fortune",
 "D - Shield",
 "D - Tactics",
 "D - Time",
 "D-Fusion",
 "D. Tribe",
 "D.D. Dynamite",
 "D.D. Trap Hole",
 "D/D Recruits",
 "D/D Reroll",
 "D/D/D Contract Change",
 "D/D/D Human Resources",
 "D2 Shield",
 "Dai Dance",
 "Damage = Reptile",
 "Damage Condenser",
 "Damage Diet",
 "Damage Gate",
 "Damage Polarizer",
 "Damage Translation",
 "Damage Vaccine Ω MAX",
 "Dances with Beasts",
 "Danger! Zone",
 "Dark Advance",
 "Dark Bribe",
 "Dark Coffin",
 "Dark Contract with Errors",
 "Dark Contract with the Eternal Darkness",
 "Dark Contract with the Witch",
 "Dark Cure",
 "Dark Deal",
 "Dark Factory of More Production",
 "Dark Horizon",
 "Dark Illusion",
 "Dark Mirror Force",
 "Dark Renewal",
 "Dark Sacrifice",
 "Dark Scheme",
 "Dark Scorpion Combination",
 "Dark Smog",
 "Dark Spirit Art - Greed",
 "Dark Spirit of the Silent",
 "Dark World Brainwashing",
 "Darkfall",
 "Darklight",
 "Darklord Descent",
 "Darklord Enchantment",
 "Darklord Rebellion",
 "Deal of Phantom",
 "Dealer's Choice",
 "Debunk",
 "Deck Devastation Virus",
 "Deep Dark Trap Hole",
 "Defenders Intersect",
 "Defense Draw",
 "Defensive Tactics",
 "Degen-Force",
 "Delta Crow - Anti Reverse",
 "Depth Amulet",
 "Des Counterblow",
 "Descending Lost Star",
 "Desert Sunlight",
 "Designer Frightfur",
 "Desperate Tag",
 "Destiny Board",
 "Destiny Mirage",
 "Destiny Signal",
 "Destruct Potion",
 "Destruction Jammer",
 "Destruction of Destiny",
 "Destruction Punch",
 "Destruction Ring",
 "Destruction Sword Flash",
 "Destruction Sword Memories",
 "Destructive Draw",
 "Detonator Circle \"A\"",
 "Devil's Portrait",
 "Diamond Dust",
 "Diamond Duston",
 "Dice It",
 "Dice Re-Roll",
 "Dice Roll Battle",
 "Dice Try!",
 "Dice-nied",
 "Diceversity",
 "Different Dimension Encounter",
 "Different Dimension Ground",
 "Dig of Destiny",
 "Dimension Gate",
 "Dimension Guardian",
 "Dimension Mirage",
 "Dimension Reflector",
 "Dimension Slice",
 "Dimension Sphinx",
 "Dimension Wall",
 "Dimensional Barrier",
 "Dimensional Inversion",
 "Dimensional Prison",
 "Dinomist Eruption",
 "Dinomist Rush",
 "Dinomists Howling",
 "Disappear",
 "Disarm",
 "Disarmament",
 "Discord",
 "Disturbance Strategy",
 "Divine Punishment",
 "Divine Relic Mjollnir",
 "Divine Wrath",
 "Dizzying Winds of Yosen Village",
 "DNA Checkup",
 "DNA Surgery",
 "DNA Transplant",
 "Do a Barrel Roll",
 "Doble Passe",
 "Doppelganger",
 "Dora of Fate",
 "Double Cipher",
 "Double Dragon Descent",
 "Double Magical Arm Bind",
 "Double Payback",
 "Double Tag Team",
 "Double Trap Hole",
 "Double-Edged Sword Technique",
 "Dragon Capture Jar",
 "Dragon's Bind",
 "Dragon's Rage",
 "Dragon's Rebirth",
 "Dragoncarnation",
 "Dragonmaid Relaxation",
 "Dragunity Legion",
 "Draining Shield",
 "Dramatic Rescue",
 "Drastic Drop Off",
 "Draw Discharge",
 "Dream Mirror Fantasy",
 "Dream Mirror Hypnagogia",
 "Dream Mirror Oneiromancy",
 "Dried Winds",
 "Driving Snow",
 "Drop Off",
 "Drowning Mirror Force",
 "Dust Storm of Gusto",
 "Dust Tornado",
 "Dustflame Blast",
 "Duston Roller",
 "Dwimmered Glimmer",
 "Earthbound Wave",
 "Earthshaker",
 "Eatgaboon",
 "Ebon Arrow",
 "Echo Oscillation",
 "Edge Hammer",
 "Eisbahn",
 "Elemental Absorber",
 "Elemental Burst",
 "Elemental Recharge",
 "Elemental Training",
 "Eliminating the League",
 "Embodiment of Apophis",
 "Emergeroid Call",
 "Empty Machine",
 "Enchanted Javelin",
 "Energy Drain",
 "Energy-Absorbing Monolith",
 "Enervating Mist",
 "Enlightenment",
 "Enma's Judgment",
 "Equip Shot",
 "Eradicator Epidemic Virus",
 "Escalation of the Monarchs",
 "Escape from the Dark Dimension",
 "Escape of the Unchained",
 "Eternal Dread",
 "Eternal Galaxy",
 "Eternal Soul",
 "Evenly Matched",
 "Evil Blast",
 "Evil Eye Defeat",
 "Evil Eye Mesmerism",
 "Evil Eye Retribution",
 "Evo-Branch",
 "Evo-Instant",
 "Evo-Singularity",
 "Evolutionary Bridge",
 "Exchange of Night and Day",
 "Exchange of the Spirit",
 "Execute Protocols",
 "Exhausting Spell",
 "Explosive Urchin",
 "Exterio's Fang",
 "Extinction on Schedule",
 "Extra Buck",
 "Eye of the Void",
 "F.A. Dead Heat",
 "F.A. Overheat",
 "Face-Off",
 "Fairy Box",
 "Fairy Wind",
 "Fairy's Hand Mirror",
 "Fake Explosion",
 "Fake Feather",
 "Fake Trap",
 "Farm Delivery",
 "Fatal Abacus",
 "Fateful Hour",
 "Feather Wind",
 "Ferret Flames",
 "Fiend Comedian",
 "Fiend Griefing",
 "Fiend's Hand Mirror",
 "Fiendish Chain",
 "Fiery Fervor",
 "Fighting Dirty",
 "Final Attack Orders",
 "Final Fusion",
 "Final Geas",
 "Fine",
 "Fire Darts",
 "Fire Formation - Kaiyo",
 "Fire Formation - Tenken",
 "Fire Formation - Tensen",
 "Fire Lake of the Burning Abyss",
 "Firewall",
 "First-Aid Squad",
 "Fish Depth Charge",
 "Fish Rain",
 "Fists of the Unrivaled Tenyi",
 "Five Brothers Explosion",
 "Flamvell Counter",
 "Flashbang",
 "Floodgate Trap Hole",
 "Fluffal Crane",
 "Follow Wing",
 "Foolish Revival",
 "Forbidden Apocrypha",
 "Forced Back",
 "Forced Ceasefire",
 "Forced Requisition",
 "Forgotten Temple of the Deep",
 "Formation Union",
 "Fortune Lady Rewind",
 "Fossil Excavation",
 "Fragment Fusion",
 "Fraud Freeze",
 "Frightfur March",
 "Froggy Forcefield",
 "Frozen Soul",
 "Fruits of Kozaky's Studies",
 "Fuh-Rin-Ka-Zan",
 "Fuhma Wave",
 "Full Force Virus",
 "Full House",
 "Full Salvo",
 "Fuse Line",
 "Fusion Fright Waltz",
 "Fusion Guard",
 "Fusion Reserve",
 "Gagagaguard",
 "Gagagarush",
 "Gagagashield",
 "Gamble",
 "Gamushara",
 "Geargiagear",
 "Gem Flash Energy",
 "Gem-Enhancement",
 "Gemini Ablation",
 "Gemini Booster",
 "Gemini Counter",
 "Gemini Trap Hole",
 "Generaider Battle",
 "Generaider Bite",
 "Generaider Territory",
 "Generation Shift",
 "Gergonne's End",
 "Get Out!",
 "Ghost of a Grudge",
 "Ghostrick Break",
 "Ghostrick Night",
 "Ghostrick Renovation",
 "Ghostrick Scare",
 "Ghostrick Vanish",
 "Ghostrick-Go-Round",
 "Ghosts From the Past",
 "Giant Trap Hole",
 "Gift Card",
 "Gift of the Mystical Elf",
 "Give and Take",
 "Gladiator Beast Charge",
 "Gladiator Beast War Chariot",
 "Gladiator Lash",
 "Gladiator Naumachia",
 "Gleipnir, the Fetters of Fenrir",
 "Glorious Illusion",
 "Goblin Fan",
 "Goblin Out of the Frying Pan",
 "Goldfish Rescue",
 "Good Goblin Housekeeping",
 "Gorgon's Eye",
 "Gottoms' Emergency Call",
 "Gozen Match",
 "Graceful Revival",
 "Graceful Tear",
 "Grand Horn of Heaven",
 "Grave Lure",
 "Grave of the Super Ancient Organism",
 "Gravelstorm",
 "Graverobber",
 "Graverobber's Retribution",
 "Graveyard of Wandering Souls",
 "Gravity Bind",
 "Gravity Collapse",
 "Graydle Combat",
 "Graydle Parasite",
 "Graydle Split",
 "Greed",
 "Grinning Grave Virus",
 "Grisaille Prison",
 "Gryphon Wing",
 "Guard Go!",
 "Guard Mines",
 "Guardragon Cataclysm",
 "Guardragon Corewakening",
 "Gust",
 "Half Counter",
 "Half or Nothing",
 "Half Unbreak",
 "Halfway to Forever",
 "Hallowed Life Barrier",
 "Hard-sellin' Goblin",
 "Hard-sellin' Zombie",
 "Harpie Lady Elegance",
 "Harpie's Feather Storm",
 "Hate Buster",
 "Haunted Shrine",
 "Hazy Glory",
 "Head Judging",
 "Heartfelt Appeal",
 "Heartless Drop Off",
 "Heavy Slump",
 "Heavy Storm Duster",
 "Heraldry Change",
 "Heraldry Record",
 "Hero Barrier",
 "Hero Blast",
 "Hero Counterattack",
 "Hero Medal",
 "Hero Ring",
 "Hero Signal",
 "Hero Spirit",
 "Hero's Rule 2",
 "Heroic Advance",
 "Heroic Gift",
 "Heroic Retribution Sword",
 "Hi-Five the Sky",
 "Hidden Soldiers",
 "Hidden Spellbook",
 "Hieratic Seal From the Ashes",
 "Hieratic Seal of Banishment",
 "Hieratic Seal of Reflection",
 "High Tide on Fire Island",
 "Hope for Escape",
 "Horn of Heaven",
 "Horn of the Phantom Beast",
 "House of Adhesive Tape",
 "Howl of the Wild",
 "Huge Revolution",
 "Human-Wave Tactics",
 "Humid Winds",
 "Hunting Instinct",
 "Hysteric Party",
 "Icarus Attack",
 "Icy Crevasse",
 "Igknight Burst",
 "Impenetrable Attack",
 "Imperial Custom",
 "Imperial Iron Wall",
 "Imperial Order",
 "Imperial Tombs of Necrovalley",
 "Induced Explosion",
 "Infernity Barrier",
 "Infernity Break",
 "Infernity Force",
 "Infernity Inferno",
 "Infernity Reflector",
 "Infestation Infection",
 "Infestation Ripples",
 "Infestation Terminus",
 "Infestation Tool",
 "Infestation Wave",
 "Infinite Dismissal",
 "Infinite Impermanence",
 "Infinite Light",
 "Infinite Machine",
 "Inherited Fortune",
 "Inspiration",
 "Intercept",
 "Interdimensional Matter Transporter",
 "Interdimensional Warp",
 "Intrigue Shield",
 "Introduction to Gallantry",
 "Inverse Universe",
 "Invincibility Barrier",
 "Inzektor Gauntlet",
 "Inzektor Orb",
 "Iron Core Luster",
 "Ivy Shackles",
 "Jam Defender",
 "Jar of Avarice",
 "Jar of Greed",
 "Jelly Cannon",
 "Jolt Counter",
 "Judgment of Anubis",
 "Judgment of the Desert",
 "Judgment of the Pharaoh",
 "Judgment of Thunder",
 "Jurassic Impact",
 "Jurrac Impact",
 "Just Desserts",
 "Justi-Break",
 "Kaiju Capture Mission",
 "Karakuri Cash Lodge",
 "Karakuri Cash Shed",
 "Karakuri Klock",
 "Karakuri Trick House",
 "Karma Cut",
 "Kickfire",
 "Kid Guard",
 "King Scarlet",
 "King's Consonance",
 "King's Synchro",
 "Koa'ki Meiru Shield",
 "Kozaky's Self-Destruct Button",
 "Kozmojo",
 "Kozmourning",
 "Krystal Avatar",
 "Kunai with Chain",
 "Labyrinth of Nightmare",
 "Lair Wire",
 "Last Counter",
 "Last Minute Cancel",
 "Last Resort",
 "Last Turn",
 "Legacy of Yata-Garasu",
 "Level Conversion Lab",
 "Level Limit - Area A",
 "Level Retuner",
 "Liberty at Last!",
 "Life Absorbing Machine",
 "Life Equalizer",
 "Light of Destruction",
 "Light of Intervention",
 "Light of Judgment",
 "Light Spiral",
 "Light-Imprisoning Mirror",
 "Lightforce Sword",
 "Lightsworn Barrier",
 "Lightsworn Judgment",
 "Limit Code",
 "Limit Impulse",
 "Limit Reverse",
 "Limiter Overload",
 "Lineage of Destruction",
 "Link Restart",
 "Link Turret",
 "Localized Tornado",
 "Loge's Flame",
 "Lone Wolf",
 "Loop of Destruction",
 "Lose 1 Turn",
 "Loss Time",
 "Lost Wind",
 "Lucky Chance",
 "Lucky Punch",
 "Lumenize",
 "Lunalight Reincarnation Dance",
 "Lunalight Serenade Dance",
 "Machine King - 3000 B.C.",
 "Macro Cosmos",
 "Madolche Lesson",
 "Madolche Nights",
 "Madolche Tea Break",
 "Madolche Waltz",
 "Madolchepalooza",
 "Magic Cylinder",
 "Magic Deflector",
 "Magic Drain",
 "Magic Jammer",
 "Magical Arm Shield",
 "Magical Explosion",
 "Magical Hats",
 "Magical Musket - Crooked Crown",
 "Magical Musket - Dancing Needle",
 "Magical Musket - Desperado",
 "Magical Musket - Fiendish Deal",
 "Magical Musket - Last Stand",
 "Magical Thorn",
 "Magician Navigation",
 "Magician's Circle",
 "Magicians' Combination",
 "Magicians' Defense",
 "Magistry Alchemist",
 "Magnet Conversion",
 "Magnet Force",
 "Majespecter Gust",
 "Majespecter Supercell",
 "Majespecter Tempest",
 "Majespecter Tornado",
 "Major Riot",
 "Malefic Claw Stream",
 "Malefic Tune",
 "Malevolent Catastrophe",
 "Malfunction",
 "Mamemaki",
 "Marincess Cascade",
 "Marincess Current",
 "Marincess Snow",
 "Marincess Wave",
 "Marshalling Field",
 "Mask of Restrict",
 "Mask of Weakness",
 "Mass Hypnosis",
 "Massivemorph",
 "Matching Outfits",
 "Mathmech Induction",
 "Mathmech Superfactorial",
 "Mayakashi Metamorphosis",
 "Megalith Emersion",
 "Megalith Promotion",
 "Meklord Factory",
 "Mektimed Blast",
 "Melodious Illusion",
 "Memory Loss",
 "Memory of an Adversary",
 "Metal Detector",
 "Metal Reflect Slime",
 "Metalfoes Combination",
 "Metalfoes Counter",
 "Metalhold the Moving Blockade",
 "Metalmorph",
 "Metamorphortress",
 "Metaphys Ascension",
 "Metaphys Dimension",
 "Metaverse",
 "Meteor Flare",
 "Meteorain",
 "Michizure",
 "Micro Ray",
 "Mind Crush",
 "Mind Drain",
 "Mind Haxorz",
 "Mind Over Matter",
 "Minefield Eruption",
 "Miniaturize",
 "Minor Goblin Official",
 "Miracle Kids",
 "Miracle Locus",
 "Miracle Restoring",
 "Miracle's Wake",
 "Miraculous Descent",
 "Mirror Force",
 "Mirror Force Launcher",
 "Mirror Gate",
 "Mirror Mail",
 "Mirror of Oaths",
 "Mirror Wall",
 "Mischief of the Gnomes",
 "Mischief of the Yokai",
 "Mispolymerization",
 "Mistake",
 "Molten Whirlwind Wall",
 "Monster Rebone",
 "Moon Dance Ritual",
 "Morphtransition",
 "Morphtronic Bind",
 "Morphtronic Forcefield",
 "Morphtronic Mix-up",
 "Morphtronic Monitron",
 "Morphtronics, Scramble!",
 "Muko",
 "Multiple Destruction",
 "Musakani Magatama",
 "Mystic Probe",
 "Mystical Refpanel",
 "Mythical Bestiamorph",
 "Narrow Pass",
 "Natural Disaster",
 "Nature's Reflection",
 "Naturia Sacred Tree",
 "Necro Fusion",
 "Necrovalley Temple",
 "Needle Ceiling",
 "Needle Wall",
 "Needlebug Nest",
 "Nega-Ton Corepanel",
 "Negate Attack",
 "Network Trap Hole",
 "NEXT",
 "Next to be Lost",
 "Nightmare Archfiends",
 "Nightmare Wheel",
 "Nine Pillars of Yang Zing",
 "Ninjitsu Art of Decoy",
 "Ninjitsu Art of Duplication",
 "Ninjitsu Art of Mirage-Transformation",
 "Ninjitsu Art of Shadow Sealing",
 "Ninjitsu Art of Super-Transformation",
 "Ninjitsu Art of Transformation",
 "Nitwit Outwit",
 "No Entry!!",
 "Non Aggression Area",
 "Non-Fusion Area",
 "Nordic Relic Brisingamen",
 "Nordic Relic Gungnir",
 "Nordic Relic Laevateinn",
 "Nordic Relic Megingjord",
 "Number Wall",
 "Numbers Overlay Boost",
 "Numinous Healer",
 "Nutrient Z",
 "Oasis of Dragon Souls",
 "Oath of Companionship",
 "Obliterate!!!",
 "Odin's Eye",
 "Offering to the Immortals",
 "Offering to the Snake Deity",
 "Oh F!sh!",
 "Oh Tokenbaum!",
 "Ojama Duo",
 "Ojama Pajama",
 "Ojama Trio",
 "Omega Summon",
 "Ominous Fortunetelling",
 "Onikuji",
 "Oops!",
 "Option Hunter",
 "Orbital Bombardment",
 "Orcust Crescendo",
 "Orcustrated Attack",
 "Orcustrated Core",
 "Orcustrated Release",
 "Ordeal of a Traveler",
 "Order to Smash",
 "Over Capacity",
 "Over Limit",
 "Overdoom Line",
 "Overwhelm",
 "Overwind",
 "Overworked",
 "Packet Link",
 "Painful Escape",
 "Paleozoic Canadia",
 "Paleozoic Dinomischus",
 "Paleozoic Eldonia",
 "Paleozoic Hallucigenia",
 "Paleozoic Leanchoilia",
 "Paleozoic Marrella",
 "Paleozoic Olenoides",
 "Paleozoic Pikaia",
 "Paradox Fusion",
 "Parallel Port Armor",
 "Parallel Selection",
 "Parry",
 "Parthian Shot",
 "Past Image",
 "Peaceful Burial",
 "Penalty Game!",
 "Pendulum Area",
 "Pendulum Back",
 "Pendulum Dimension",
 "Pendulum Hole",
 "Pendulum Reborn",
 "Pendulum Switch",
 "Performapal Call",
 "Performapal Pinch Helper",
 "Performapal Revival",
 "Performapal Show Down",
 "Personal Spoofing",
 "Phantasm Spiral Assault",
 "Phantasm Spiral Battle",
 "Phantasm Spiral Power",
 "Phantom Hand",
 "Phantom Knights' Fog Blade",
 "Phantom Knights' Sword",
 "Phantom Knights' Wing",
 "Pharaoh's Treasure",
 "Phoenix Wing Wind Blast",
 "Photon Change",
 "Photon Current",
 "Physical Double",
 "Pikeru's Circle of Enchantment",
 "Pikeru's Second Sight",
 "Pineapple Blast",
 "Pinpoint Guard",
 "Pitch-Black Power Stone",
 "Pixie Ring",
 "Planckton",
 "Planet Pollutant Virus",
 "Plant Food Chain",
 "Pole Position",
 "Pollinosis",
 "Portable Battery Pack",
 "Poseidon Wave",
 "Power Break",
 "Power Frame",
 "Power Wall",
 "Power-Up Adapter",
 "Powerful Rebirth",
 "Powerhold the Moving Battery",
 "Powersink Stone",
 "Prank-Kids Plan",
 "Predaplanet",
 "Predaplanning",
 "Premature Return",
 "Prepare to Strike Back",
 "Present Card",
 "Prideful Roar",
 "Prologue of the Destruction Swordsman",
 "Proof of Powerlessness",
 "Proton Blast",
 "Psi-Curse",
 "PSY-Frame Accelerator",
 "PSY-Frame Overload",
 "Psychic Overload",
 "Psychic Reactor",
 "Psychic Rejuvenation",
 "Psychic Shockwave",
 "Psychic Soul",
 "Psychic Trigger",
 "Psychic Tuning",
 "Pulling the Rug",
 "Pulse Mines",
 "Punch-in-the-Box",
 "Puppet Parade",
 "Purge Ray",
 "Purushaddoll Aeon",
 "Puzzle Reborn",
 "Pyramid of Light",
 "Pyro Clock of Destiny",
 "Pyroxene Fusion",
 "Qlife's End",
 "Qlimate Change",
 "Qlipper Launch",
 "Quaking Mirror Force",
 "Quantum Cat",
 "Queen's Pawn",
 "Radiant Mirror Force",
 "Raging Cloudian",
 "Raidraptor - Readiness",
 "Raidraptor - Return",
 "Raidraptor Replica",
 "Raigeki Bottle",
 "Raigeki Break",
 "Rain Storm",
 "Rainbow Gravity",
 "Rainbow Life",
 "Rainbow Path",
 "Raptor's Gust",
 "Rare Metalmorph",
 "Ray of Hope",
 "Re-dyce-cle",
 "Re-qliate",
 "Ready for Intercepting",
 "Really Eternal Rest",
 "Reanimation Wave",
 "Rebirth of Parshath",
 "Rebound",
 "Recall",
 "Reckless Greed",
 "Reckoned Power",
 "Recoded Alive",
 "Red Carpet",
 "Red Cocoon",
 "Red Reboot",
 "Red Screen",
 "Red Supremacy",
 "Red-Eyes Burn",
 "Red-Eyes Fang with Chain",
 "Red-Eyes Spirit",
 "Regretful Rebirth",
 "Reinforce Truth",
 "Reinforced Space",
 "Reinforcements",
 "Reject Reborn",
 "Relay Soul",
 "Release from Stone",
 "Release, Reverse, Burst",
 "Relieve Monster",
 "Remote Rebirth",
 "Remote Revenge",
 "Remove Brainwashing",
 "Renewal of the World",
 "Reshaddoll Incarnation",
 "Respect Play",
 "Resurgam Xyz",
 "Retort",
 "Return",
 "Return from the Different Dimension",
 "Return of the Red-Eyes",
 "Return of the Six Samurai",
 "Return of the Zombies",
 "Return Soul",
 "Reversal of Fate",
 "Reverse Glasses",
 "Reverse Reuse",
 "Reverse Trap",
 "Revival Gift",
 "Revival of the Immortals",
 "Ring of Destruction",
 "Riryoku Field",
 "Rise of the Snake Deity",
 "Rise to Full Height",
 "Rising Energy",
 "Rite of Spirit",
 "Ritual Beast Ambush",
 "Ritual Beast Steeds",
 "Ritual Buster",
 "Ritual Sealing",
 "Rivalry of Warlords",
 "Roar of the Earthbound Immortal",
 "Roaring Earth",
 "Robbin' Goblin",
 "Robbin' Zombie",
 "Rock Bombardment",
 "Rocket Hand",
 "Roll Out!",
 "Rope of Life",
 "Royal Command",
 "Royal Decree",
 "Royal Oppression",
 "Royal Prison",
 "Royal Surrender",
 "Royal Writ of Taxation",
 "Saber Hole",
 "Safe Zone",
 "Sakuretsu Armor",
 "Salamangreat Gift",
 "Salamangreat Rage",
 "Salamangreat Roar",
 "Sanguine Swamp",
 "Saryuja's Shackles",
 "Scramble Egg",
 "Scrap Crash",
 "Scrap Rage",
 "Scrap-Iron Scarecrow",
 "Scrap-Iron Signal",
 "Scrap-Iron Statue",
 "Scrubbed Raid",
 "Scrum Force",
 "Sea Stealth Attack",
 "Seal of Wickedness",
 "Sealing Ceremony of Katon",
 "Sealing Ceremony of Mokuton",
 "Sealing Ceremony of Raiton",
 "Sealing Ceremony of Suiton",
 "Second Expedition into Danger!",
 "Secret Barrel",
 "Secret Blast",
 "Secrets of the Gallant",
 "Security Orb",
 "Seismic Shockwave",
 "Self-Destruct Button",
 "Senka Legend - Champion's Bravery at Changban Bridge",
 "Sentence of Doom",
 "Serpent Suppression",
 "Setuppercut",
 "Seven Tools of the Bandit",
 "Shaddoll Core",
 "Shadow Impulse",
 "Shadow of Eyes",
 "Shadow Spell",
 "Shadow-Imprisoning Mirror",
 "Shapesister",
 "Shattered Axe",
 "Shield Handler",
 "Shield Spear",
 "Shien's Scheme",
 "Shift",
 "Shining Silver Force",
 "Shinobird Salvation",
 "Shiranui Style Samsara",
 "Shiranui Style Success",
 "Shiranui Style Swallow's Slash",
 "Shooting Star",
 "Showdown of the Secret Sense Scroll Techniques",
 "Side Effects?",
 "Simorgh Sky Battle",
 "Simultaneous Loss",
 "Sinister Seeds",
 "Sinister Shadow Games",
 "Sinister Yorishiro",
 "Six Strike - Thunder Blast",
 "Six Style - Dual Wield",
 "Sixth Sense",
 "Skill Drain",
 "Skill Prisoner",
 "Skill Successor",
 "Skull Dice",
 "Skull Invitation",
 "Skull Lair",
 "Slip of Fortune",
 "Slip Summon",
 "Smashing Horn",
 "Smile Potion",
 "Snake Deity's Command",
 "Snake Fang",
 "Snake Whistle",
 "Snowman Effect",
 "Solar Ray",
 "Solemn Authority",
 "Solemn Judgment",
 "Solemn Scolding",
 "Solemn Strike",
 "Solemn Warning",
 "Solemn Wishes",
 "Solomon's Lawbook",
 "Sonic Boom",
 "Sonic Stun",
 "Soul Demolition",
 "Soul Drain",
 "Soul Levy",
 "Soul Resurrection",
 "Soul Rope",
 "Soul Strike",
 "Soul Transition",
 "Sound the Retreat!",
 "Space Dragster",
 "Spacegate",
 "Spatial Collapse",
 "Spell Purification",
 "Spell Reclamation",
 "Spell Shield Type-8",
 "Spell Vanishing",
 "Spell-Stopping Statute",
 "Spellbinding Circle",
 "Spider Egg",
 "Spikeshield with Chain",
 "Spin Turn",
 "Spirit Barrier",
 "Spirit Force",
 "Spirit's Invitation",
 "Spiritual Earth Art - Kurogane",
 "Spiritual Fire Art - Kurenai",
 "Spiritual Light Art - Hijiri",
 "Spiritual Swords of Revealing Light",
 "Spiritual Water Art - Aoi",
 "Spiritual Wind Art - Miyabi",
 "Splash Capture",
 "SPYRAL GEAR - Utility Wire",
 "SPYRAL MISSION - Recapture",
 "SPYRAL MISSION - Rescue",
 "Stalemate",
 "Star Siphon",
 "Stardust Flash",
 "Stardust Mirage",
 "Stardust Re-Spark",
 "Stardust Wish",
 "Starlight Road",
 "Statue of Anguish Pattern",
 "Statue of the Wicked",
 "Staunch Defender",
 "Stellarnova Alpha",
 "Stellarnova Wave",
 "Stonehenge Methods",
 "Storm Dragon's Return",
 "Storming Mirror Force",
 "Straight Flush",
 "Strike Slash",
 "Stronghold the Moving Fortress",
 "Stygian Dirge",
 "Subsurface Stage Divers",
 "Subterror Behemoth Burrowing",
 "Subterror Final Battle",
 "Subterror Succession",
 "Success Probability 0%",
 "Summon Gate",
 "Summon Limit",
 "Super Junior Confrontation",
 "Super Quantal Mech Sword - Magnaslayer",
 "Super Quantal Union - Magnaformation",
 "Super Rush Recklessly",
 "Super Soldier Rebirth",
 "Super Soldier Shield",
 "Super Team Buddy Force Unite!",
 "Supercharge",
 "Supernatural Regeneration",
 "Supreme Rage",
 "Survival Instinct",
 "Survival of the Fittest",
 "Survival's End",
 "Swallow Flip",
 "Swamp Mirrorer",
 "Swift Samurai Storm!",
 "Swiftstrike Armor",
 "Switcheroroo",
 "Sylvan Blessing",
 "Sylvan Waterslide",
 "Synchro Barrier",
 "Synchro Call",
 "Synchro Deflector",
 "Synchro Ejection",
 "Synchro Material",
 "Synchro Strike",
 "Synthetic Seraphim",
 "Tachyon Chaos Hole",
 "Tachyon Spiral Galaxy",
 "Tachyon Transmigration",
 "Tactical Exchanger",
 "Talisman of Spell Sealing",
 "Taunt",
 "Telepathic Power",
 "Terra Firma Gravity",
 "Terrible Deal",
 "TG-SX1",
 "TG1-EM1",
 "TGX3-DX2",
 "That Six",
 "That Wacky Alchemy!",
 "The Deep Grave",
 "The Door of Destiny",
 "The Dragon's Bead",
 "The Emperor's Holiday",
 "The Eye of Truth",
 "The First Monarch",
 "The First Sarcophagus",
 "The Forceful Checkpoint",
 "The Forces of Darkness",
 "The Gift of Greed",
 "The Golden Apples",
 "The Grave of Enkindling",
 "The Huge Revolution is Over",
 "The League of Uniform Nomenclature",
 "The Monarchs Awaken",
 "The Monarchs Erupt",
 "The Paths of Destiny",
 "The Phantom Knights of Dark Gauntlets",
 "The Phantom Knights of Lost Vambrace",
 "The Phantom Knights of Mist Claws",
 "The Phantom Knights of Shade Brigandine",
 "The Phantom Knights of Shadow Veil",
 "The Phantom Knights of Tomb Shield",
 "The Phantom Knights of Wrong Magnetring",
 "The Prime Monarch",
 "The Regulation of Tribe",
 "The Return to the Normal",
 "The Revenge of the Normal",
 "The Sanctified Darklord",
 "The Selection",
 "The Six Shinobi",
 "The Spell Absorbing Life",
 "The Transmigration Prophecy",
 "The Traveler and the Burning Abyss",
 "The Ultimate Creature of Destruction",
 "The Weather Auroral Canvas",
 "The Weather Rainbowed Canvas",
 "The Weather Thundery Canvas",
 "There Can Be Only One",
 "Threatening Roar",
 "Three of a Kind",
 "Three Strikes Barrier",
 "Thunder Dragon Discharge",
 "Thunder Dragons' Hundred Thunders",
 "Thunder of Ruler",
 "Tiki Curse",
 "Tiki Soul",
 "Time Machine",
 "Time Pendulumgraph",
 "Time Seal",
 "Time Thief Flyback",
 "Time Thief Retrograde",
 "Time-Space Trap Hole",
 "Tindangle Delaunay",
 "Token Feastevil",
 "Token Stampede",
 "Toll Hike",
 "Toon Briefcase",
 "Toon Defense",
 "Toon Mask",
 "Tornado Wall",
 "Torrential Reborn",
 "Torrential Tribute",
 "Tour of Doom",
 "Tower of Babel",
 "Tragedy",
 "Training Fur Hire, Fur All Your Training Needs",
 "Transmigration Break",
 "Transmission Gear",
 "Trap Dustshoot",
 "Trap Hole",
 "Trap Hole of Spikes",
 "Trap Jammer",
 "Trap of Board Eraser",
 "Trap of Darkness",
 "Trap of the Imperial Tomb",
 "Trap Reclamation",
 "Trap Stun",
 "Trap Trick",
 "Traptrix Trap Hole Nightmare",
 "Treacherous Trap Hole",
 "Treasure Map",
 "Treaty on Uniform Nomenclature",
 "Tri-and-Guess",
 "Triamid Pulse",
 "Trick Box",
 "Trickstar Reincarnation",
 "Triggered Summon",
 "Trojan Blast",
 "Trojan Gladiator Beast",
 "True Draco Apocalypse",
 "True King's Return",
 "Tuner Capture",
 "Tuner's Barrier",
 "Tuner's Scheme",
 "Turnabout",
 "Tutan Mask",
 "Twilight Cloth",
 "Twilight Eraser",
 "Two-Pronged Attack",
 "Type Zero Magic Crusher",
 "Typhoon",
 "Tyrant Wing",
 "Tyrant's Tantrum",
 "Tyrant's Temper",
 "Tyrant's Throes",
 "Tyrant's Tirade",
 "Tyrant's Tummyache",
 "U.A. Penalty Box",
 "Ultimate Crystal Magic",
 "Ultimate Earthbound Immortal",
 "Ultimate Fire Formation - Seito",
 "Ultimate Fire Formation - Sinto",
 "Ultimate Offering",
 "Ultimate Providence",
 "Unbreakable Spirit",
 "Underworld Egg Clutch",
 "Unending Nightmare",
 "Unification",
 "Unification of the Cubic Lords",
 "Unified Front",
 "Union Scramble",
 "United Front",
 "Universal Adapter",
 "Unpossessed",
 "Until Noble Arms are Needed Once Again",
 "Unwavering Bond",
 "Updraft",
 "Urgent Ritual Art",
 "Urgent Tuning",
 "Utopian Aura",
 "Vain Betrayer",
 "Vampire Awakening",
 "Vampire Domination",
 "Vampire Takeover",
 "Vanity's Call",
 "Vanity's Emptiness",
 "Vanquishing Light",
 "Variable Form",
 "Vendread Daybreak",
 "Vendread Reorigin",
 "Vendread Reunion",
 "Vendread Revolution",
 "Venom Burn",
 "Virus Cannon",
 "Void Feast",
 "Void Launch",
 "Void Purification",
 "Void Trap Hole",
 "Volcanic Eruption",
 "Volcanic Recharge",
 "W Nebula Meteorite",
 "Waboku",
 "Waking the Dragon",
 "Wall of Disruption",
 "Wall of Revealing Light",
 "Wall of Thorns",
 "Waterfall of Dragon Souls",
 "Wattcancel",
 "Wattcannon",
 "Wattkeeper",
 "Weed Out",
 "Whirlwind of Gusto",
 "White Hole",
 "White Howling",
 "Wicked Rebirth",
 "Widespread Dud",
 "Widespread Ruin",
 "Wild Tornado",
 "Windstorm of Etaqua",
 "Wiretap",
 "Witch's Strike",
 "Witchcrafter Masterpiece",
 "Wolf in Sheep's Clothing",
 "Wonder Garage",
 "Wonder Xyz",
 "World Legacy Awakens",
 "World Legacy Bestowal",
 "World Legacy Cliffhanger",
 "World Legacy Collapse",
 "World Legacy Landmark",
 "World Legacy Pawns",
 "World Legacy Struggle",
 "World Legacy Trap Globe",
 "World Legacy Whispers",
 "World Legacy's Mind Meld",
 "World Legacy's Secret",
 "World Legacy's Sorrow",
 "World Reassembly",
 "World Suppression",
 "Xing Zhen Hu",
 "Xing Zhen Hu Replica",
 "Xyz Block",
 "Xyz Dimension Splash",
 "Xyz Effect",
 "Xyz Reborn",
 "Xyz Reflect",
 "Xyz Revenge Shuffle",
 "Xyz Reversal",
 "Xyz Soul",
 "Xyz Tribalrivals", "Xyz Universe", "Xyz Veil", "Xyz Wrath", "Xyz Xtreme !!", "Yang Zing Brutality", "Yang Zing Creation", "Yang Zing Unleashed", "Yosenjus' Secret Move", "Yosenjus' Sword Sting", "You're in Danger!", "Zefra Divine Strike", "Zefra War", "Zekt Conversion", "Zenmaiday", "Zenmailstrom", "Zenmairch", "Zero Force", "Zero Gravity","Zero-Day Blaster", "Zoma the Spirit", "Zoodiac Combo","Zoodiac Gathering"]
	end
end